### ISSUE TITLE
Error when importing some vue empty component to other vue component

### ISSUE THREAD

**Issue by TelyakovKostya** [apeschar/esbuild-vue#1]
Hi! When i'm try to import empty sfc to other sfc, esbuild-vue plugin throw Error, but not explained what kind of error happened.

```esbuild node build.js
 > node_modules/@vue/component-compiler/dist/assembler.js:343:29: error: [plugin: vue] Invalid mapping: {"generated":{"line":2,"column":0},"source":"","original":{"line":1,"column":0},"name":null}
    343 │                 mapGenerator.addMapping({
        ╵                              ^
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/konstantin/Desktop/esbuild/node_modules/source-map/lib/source-map-generator.js:298:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/konstantin/Desktop/esbuild/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Users/konstantin/Desktop/esbuild/node_modules/@vue/component-compiler/dist/assembler.js:343:30
    at Array.forEach (<anonymous>)
    at assembleFromSource (/Users/konstantin/Desktop/esbuild/node_modules/@vue/component-compiler/dist/assembler.js:330:15)
    at Object.assemble (/Users/konstantin/Desktop/esbuild/node_modules/@vue/component-compiler/dist/assembler.js:7:12)
    at module.exports (/Users/konstantin/Desktop/esbuild/node_modules/esbuild-vue/src/worker.js:36:36)
    at /Users/konstantin/Desktop/esbuild/node_modules/piscina/dist/src/worker.js:141:32

   node_modules/esbuild-vue/src/index.js:23:12: note: This error came from the "onLoad" callback registered here
     23 │       build.onLoad({ filter: /[^/]\.vue$/ }, async ({ path }) => {
        ╵             ~~~~~~
    at setup (/Users/konstantin/Desktop/esbuild/node_modules/esbuild-vue/src/index.js:23:13)
    at handlePlugins (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1021:7)
    at /Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1745:17
    at new Promise (<anonymous>)
    at Object.build (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1744:14)
    at Object.build (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1620:51)
    at Object.<anonymous> (/Users/konstantin/Desktop/esbuild/build.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)

   component.vue:7:26: note: The plugin "vue" was triggered by this import
      7 │ import someComponent from './someComponent.vue'
        ╵                           ~~~~~~~~~~~~~~~~~~~~~

(node:61495) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
node_modules/@vue/component-compiler/dist/assembler.js:343:29: error: [plugin: vue] Invalid mapping: {"generated":{"line":2,"column":0},"source":"","original":{"line":1,"column":0},"name":null}
    at failureErrorWithLog (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1446:15)
    at /Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1128:28
    at runOnEndCallbacks (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:918:63)
    at buildResponseToResult (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1126:7)
    at /Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:1233:14
    at /Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/konstantin/Desktop/esbuild/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
(node:61495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by apeschar** [comment]
Thanks for reporting this. The issue should be fixed in the latest version 0.3.2. [See my comment on your PR.](https://github.com/apeschar/esbuild-vue/pull/2#issuecomment-856729567)
